### ISSUE TITLE
How to add Semaphore and uvloop?

### ISSUE THREAD

**Issue by singdoo** [kelseykm/ketter#1]
How to add Semaphore and uvloop?

**Comment by kelseykm** [comment]
_Semaphores now used, see source code._

If you would like to use uvloop, all you need to do is install the uvloop event policy before calling asyncio.run. So you would insert
`uvloop.install()`
or
`asyncio.set_event_loop_policy(uvloop.EventLoopPolicy())`
before
`asyncio.run(main())`

(You would obviously need to have imported uvloop before using it.)
